name: Lefthook

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    permissions:
      contents: read
    uses: ffreis-org/ffreis-workflows-general/.github/workflows/general-lefthook.yml@5dfbb4986ceb88f6518fa719da3a255294cf03cf
    with:
      working-directory: "."
      go-version: "1.25.8"
      lefthook-bootstrap-command: "make lefthook-bootstrap"
      lefthook-bin: ".bin/lefthook"
